FROM apache/airflow:2.8.0-python3.11

# Install packages as airflow user
USER airflow
RUN pip install --no-cache-dir \
    kafka-python \
    pandas \
    sqlalchemy \
    psycopg2-binary \
    openpyxl